server {
    listen       443 ssl;
    listen       443 quic reuseport;
    listen       80;

    server_name  localhost;

    ssl_certificate        /etc/angie/ssl/certs/common.local.crt;
    ssl_certificate_key    /etc/angie/ssl/keys/common.local.key;
    ssl_protocols          TLSv1.2 TLSv1.3;

    ssl_client_certificate /etc/angie/ssl/certs/trusted_cas.crt;
    ssl_verify_client      optional_no_ca;

    ssl_session_cache      shared:SSL:10m;
    ssl_session_timeout    10m;
    ssl_session_tickets    on;

    http2 on;
    http3 on;

    access_log  /var/log/angie/host.access.log  extended;

    default_type text/plain;



    location / {



        if ( $scheme = http ) {
            return 301 "https://$host$uri$is_args$args";
            break;
        }



        add_header Strict-Transport-Security max-age=31536000;
        add_header Alt-Svc 'h3=":443"; ma=86400';

        set $var_common_message "\nHello, dear $remote_addr:$remote_port :)\n\nWe agreed on $ssl_protocol using '$ssl_cipher'\n";




        if ($ssl_client_verify = SUCCESS ) {

            return 200 "
$var_common_message 
Your certificate is VALID!

         DN | $ssl_client_s_dn
         SN | $ssl_client_serial
 Valid  for | $ssl_client_v_remain days
 Valid from | $ssl_client_v_start
 Valid till | $ssl_client_v_end
Issuer's DN | $ssl_client_i_dn

/*
 * --- THINK LIKE ANGIE DOES! BE AN ANGIE! ---
 */\n\n";
            break;
        }



        if ($ssl_client_verify = NONE ) {

            return 200 "
$var_common_message
You have not used any client's certificate!

/*
 * WE WILL NOT SHARE WITH YOU OUR TOP-SECTETS BECAUSE OF HAVING NO IDEA WHO YOU ARE.
 */\n\n";
            break;
        }



        if ($ssl_client_verify ~ FAILED:(.*)) {
            return 400 "
$var_common_message
Your certificate is INVALID with the comment: '$1'!

         DN | $ssl_client_s_dn
         SN | $ssl_client_serial
 Valid  for | $ssl_client_v_remain days
 Valid from | $ssl_client_v_start
 Valid till | $ssl_client_v_end
Issuer's DN | $ssl_client_i_dn

/*
 * WE WILL NOT SHARE WITH YOU OUR TOP SECTETS BECAUSE WE CANNOT TRUST YOUR CERTIFICATE.
 */\n\n";
            break;
        }

    }



    location /status/ {
        api     /status/;
        allow   127.0.0.1;
        deny    all;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/angie/html;
    }

}
